# Welcome to Numpy 

In [1]:
import numpy as np
print(np.__version__)


1.25.1


In [2]:
myarr = np.array([[1,5,25,8]], np.int64)


In [3]:
myarr

array([[ 1,  5, 25,  8]], dtype=int64)

In [4]:
type(myarr)

numpy.ndarray

In [5]:
myarr[0,1]

5

In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.dtype

dtype('int64')

In [8]:
myarr[0,1]=10-2

In [9]:
myarr

array([[ 1,  8, 25,  8]], dtype=int64)

# Arry creation conversion from other python structures

In [10]:
newarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
newarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
newarray.size

9

In [13]:
newarray.shape

(3, 3)

In [14]:
newarray.dtype

dtype('int32')

In [15]:
z= np.zeros((2,5))

In [16]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
z.dtype

dtype('float64')

In [18]:
z.shape

(2, 5)

In [19]:
rr = np.arange(10)

In [20]:
rr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
lsp = np.linspace(1,10,5)

In [22]:
lsp

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
lsppp = np.linspace(1,5,5)

In [24]:
lsppp

array([1., 2., 3., 4., 5.])

In [25]:
emp = np.empty((4,6))

In [26]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.20161118e-306, 1.60219985e-306, 6.23060065e-307],
       [2.22526399e-307, 6.23053614e-307, 1.29060871e-306,
        6.23055651e-307, 1.06811422e-306, 3.56043054e-307],
       [1.37961641e-306, 9.45697982e-308, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 6.23053614e-307, 1.33511562e-306,
        6.89805151e-307, 8.90111708e-307, 2.56765117e-312]])

In [27]:
empl = np.empty_like(lsppp)

In [28]:
empl

array([1., 2., 3., 4., 5.])

In [29]:
empl.shape

(5,)

In [30]:
ide = np.identity(8)

In [31]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
ide.shape

(8, 8)

In [33]:
arr = np.arange(99)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr.reshape(3,33)                    #for reshape check 2 digits multiplication ex 3*33 = 99 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
arr = arr.reshape(3,33)   #now the arr structer is change as you assign as variable 

In [38]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [39]:
arr=arr.ravel()   # to reasign the shape as 1D array so use ravel() function 

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [41]:
arr.shape

(99,)

In [42]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [43]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
s = x.sum(axis=0)     #axis =0 means its row (row1 ,row 2 ...)

In [45]:
s

array([12, 15, 18])

In [46]:
ss = x.sum(axis=1)      #axis =1 means its row (column 1  ,column 2 ...)

In [47]:
ss

array([ 6, 15, 24])

In [48]:
x.T                 # .T means Transpose (it will convert row into column and column into row)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
x.flat    #flat makes arrya 1D likein one row then we can use for loop 

In [51]:
for item in x.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [52]:
x.ndim  # .ndim tells you number of dimension

2

In [53]:
x.size

9

In [54]:
x.nbytes  # .nbytes tell you how many bytes / storage consuming

36

In [55]:
one = np.array([6,2,3,43,556,23,983,7,9])

In [56]:
one.argmax()            # .argmax() is to find index of maximum number

6

In [57]:
one.argmin()                  # .argmin() is to find index of minimum number

1

In [59]:
one.argsort()                     #  .argsort give you asecending index of array ndits type

array([1, 2, 0, 7, 8, 5, 3, 4, 6], dtype=int64)

In [61]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
x.argmax()

8

In [63]:
x.argmin()

0

In [65]:
x.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [66]:
x.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [69]:
x=x.astype(np.int32)

In [72]:
x.dtype

dtype('int32')

In [73]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
x.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [75]:
x.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [78]:
x.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
x.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [82]:
x.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
x.reshape(9,)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
x1 = np.array([[1, 5, 3],
       [4, 9, 6],
       [2, 8, 1]])

In [88]:
x1

array([[1, 5, 3],
       [4, 9, 6],
       [2, 8, 1]])

In [89]:
x+x1

array([[ 2,  7,  6],
       [ 8, 14, 12],
       [ 9, 16, 10]])

In [92]:
[34,838] + [32,43]   #in python you cant do addition like this but numpy you cn do 

[34, 838, 32, 43]

In [93]:
x*x1

array([[ 1, 10,  9],
       [16, 45, 36],
       [14, 64,  9]])

In [94]:
 x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
np.sqrt(x)                       # np.sqrt give squart root of that number

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [100]:
x.sum()

45

In [101]:
x.max()

9

In [102]:
x.min()

1

In [104]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
np.where(x>5)                # it shows where 5 is greter in ans it give index of rwos and columns

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [106]:
np.count_nonzero(x)

9

In [107]:
np.nonzero(x)                # it gives nonzeroo in index tuple format

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [108]:
import sys

In [109]:
py_ar = [0,23,45,10]  # its python array

In [110]:
np_ar = np.array(py_ar)   #its numpy array

In [111]:
sys.getsizeof(1) * len(py_ar)     # calculates the approximate memory usage in bytes of a Python list py_ar

112

In [114]:
np_ar.itemsize * np_ar.size      # np_ar.size calculates the memory usage in bytes of a NumPy array 

16

In [115]:
# this shoes numpy use less space compare to python

In [117]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])